"""empty message

Revision ID: 1292bc8b5a6f
Revises: 0cc7d65ca32e
Create Date: 2025-01-03 22:35:24.004707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1292bc8b5a6f'
down_revision = '0cc7d65ca32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
